"use client";
import Head from "next/head";
import React, { Fragment, useEffect } from "react";

type helmet = {
  title: string;
};

export default function Helmet({ title }: helmet) {
  useEffect(() => {
    document.title = `karma shop - ${title}`;
  }, [title]);
  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </Fragment>
  );
}
